

# This file was *autogenerated* from the file merkle_trees.sage
from sage.all_cmdline import *   # import sage library

_sage_const_0 = Integer(0)#Docs available at https://github.com/Tierion/pymerkletools
import merkletools;
import hashlib;
load('merkletools.sage')
load('merkle_trees_utils.sage')

mt = MerkleTools()

data = ["1","2","3","4","5"]

#Create the Merkle Tree
MerkleTree(data)

#Get tree root
merkleRoot =  mt.get_merkle_root()

#Get authentication path
auth_path = mt.get_proof(_sage_const_0 )
print(auth_path)

'''
if mt.is_ready:
    merkleRoot =  mt.get_merkle_root()
    for i in range(0,num_blocks):
        targetHash = hashlib.sha256()
        targetHash.update(blocks[i].encode('utf-8'))
        targetHash = targetHash.hexdigest()
        proof = mt.get_proof(i)
        is_valid = mt.validate_proof(proof, targetHash, merkleRoot)
        if is_valid:    print("Block no."+str(i+1).zfill(2)+": VALID")
        else:   print("Block no."+str(i+1).zfill(2)+": NOT VALID")
else: print("Tree not created")
'''



